# data parameters
data_path:
save_path: checkpoint/train
resume: False
model_name: BaseCNN
batch_size: 16
device: mps

# training parameters
epoch: 3
lr: 0.0001
beta1: 0.9
beta2: 0.999
e: 1e-08
print_iter: 1000

# test parameters
model_path: checkpoint/train/2.pth